spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: can
    password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5433/coursedb
    driver-class-name: org.postgresql.Driver
    username: can
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  exchange: course.internal.exchange
  routing-key: course.student.enrolled.routing-key
  queue: course.student.enrolled.queue
  exam-submitted:
    routing-key: course.exam.submitted.routing-key
    queue: course.exam.submitted.queue

server:
  port: 8082



